[package]
name = "rmenu_history"
version = "0.2.0"
authors = ["Jens Fredskov <jsfr@users.noreply.github.com>"]
edition = "2021"
include = ["src/**/*", "build.rs", "!**/*_test.*"]

[dependencies]
anyhow = "1.0.57"
clap = { version = "3.1.18", features = ["derive"] }
