[package]
name = "rmenu"
version = "0.1.0"
authors = ["Jens Fredskov <jensfredskov@protonmail.ch>"]
edition = "2018"

[lib]
name = "utils"
path = "src/utils.rs"

[dependencies]
structopt = "*"
failure = "*"
exitfailure = "*"
