[workspace]
members = ["rmenu_history", "rmenu"]

[profile.release]
# Consider if this is better or worse. We want fast boot time not smaller
# opt-level = 'z'
lto = true
panic = 'abort'
codegen-units = 1
strip = true
