[package]
name = "rmenu"
version = "0.2.0"
authors = ["Jens Fredskov <jsfr@users.noreply.github.com>"]
edition = "2021"

[dependencies]
anyhow = "1.0.57"
clap = { version = "3.1.18", features = ["derive"] }
druid = { git = "https://github.com/linebender/druid.git", features = ["im"] }
druid-shell = { git = "https://github.com/linebender/druid.git" }
