[package]
name = "rmenu"
version = "0.1.0"
authors = ["Jens Fredskov <jsfr@users.noreply.github.com>"]
edition = "2018"

[dependencies]
clap = "3.0.0-beta.2"
druid = { git = "https://github.com/linebender/druid.git", features = ["im"] }
druid-shell = { git = "https://github.com/linebender/druid.git" }
exitfailure = "0.5.1"
failure = "0.1.8"

[build-dependencies]
clap = "3.0.0-beta.2"
clap_generate = "3.0.0-beta.2"
druid = { git = "https://github.com/linebender/druid.git", features = ["im"] }
failure = "0.1.8"
