[package]
name = "rmenu"
version = "0.1.0"
authors = ["Jens Fredskov <jensfredskov@protonmail.ch>"]
edition = "2018"

[dependencies]
structopt = "*"
failure = "*"
exitfailure = "*"
glutin = "*"
gl = "*"
hex = "*"
regex = "*"
