[package]
name = "rmenu"
version = "0.1.0"
authors = ["Jens Fredskov <jsfr@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
druid = { git = "https://github.com/linebender/druid.git" }
druid-shell = { git = "https://github.com/linebender/druid.git" }
exitfailure = "0.5.1"
failure = "0.1.8"
