[package]
name = "rmenu"
version = "0.3.0"
authors = ["Jens Fredskov <jsfr@users.noreply.github.com>"]
edition = "2021"
description = "Shows a selector to fuzzy select between a list of items"

[dependencies]
anyhow = "1.0.65"
clap = { version = "4.0.8", features = ["derive"] }
druid = { git = "https://github.com/linebender/druid.git", features = ["im"] }
druid-shell = { git = "https://github.com/linebender/druid.git" }
jaq-core = "0.8.1"
serde_json = "1.0.85"
