#!/usr/bin/env bash

function get_history_file() {
    cache_dir=${XDG_CACHE_HOME:-"$HOME/.cache"}

    if [ -d "$cache_dir" ]; then
        mkdir -p "$cache_dir/rmenu" &>/dev/null
        history_file="$cache_dir/rmenu/launch_history"
    else
        history_file="$HOME/.rmenu_launch_history" # if no xdg dir, fall back to dotfile in ~
    fi

    if [ ! -f "$history_file" ]; then
        touch "$history_file"
    fi

    echo "$history_file"
}

function get_blacklist() {
    config_dir=${XDG_CONFIG_HOME:-"$HOME/.config"}

    if [ -d "$config_dir" ]; then
        mkdir -p "$config_dir"/rmenu &>/dev/null
        config_file="$config_dir/rmenu/launch_blacklist"
    else
        config_file="$HOME/.rmenu_launch_blacklist" # if no xdg dir, fall back to dotfiles in ~
    fi

    echo "$config_file"
}

function check_commands() {
    for command in "$@"; do
        if ! command -v "$command" &> /dev/null; then
            echo "'$command' could not be found, but is required."
            exit 1
        fi
    done
}

check_commands fd jq rmenu rmenu_history

BLACKLIST=$(sort "$(get_blacklist)")
SOURCES=(
    "/Applications"
    "$HOME/Applications"
    "/System/Applications"
    "/System/Applications/Utilities"
    "/System/Library/CoreServices"
    "/Library/PreferencePanes"
    "$HOME/Library/PreferencePanes"
    "/System/Library/PreferencePanes"
)
OPTIONS=$(comm -23 <(fd . -e app -e prefPane --exact-depth 1 "${SOURCES[@]}" | sort) <(echo "$BLACKLIST") \
    | jq -Rrnc '[inputs] | .[] | {name: . | split("/")[-2] | sub(".prefPane$|.app$";""), path: .}')

HISTORY_FILE=$(get_history_file)

SELECTION=$(echo "$OPTIONS" | rmenu_history "$HISTORY_FILE" sort | rmenu --filter ".name" "$@")

# If nothing was selected exit
if [[ -z $SELECTION ]]; then
    exit
fi

# Open selection
open "$(echo $SELECTION | jq -r '.path')"

# Update history file with selection
rmenu_history "$HISTORY_FILE" update "$SELECTION"
