#!/usr/bin/env bash

function get_history_file() {
    cachedir=${XDG_CACHE_HOME:-"$HOME/.cache"}

    if [ -d "$cachedir" ]; then
        mkdir -p "$cachedir/rmenu" &>/dev/null
        history_file="$cachedir/rmenu/run_history"
    else
        history_file="$HOME/.rmenu_run_history" # if no xdg dir, fall back to dotfile in ~
    fi

    if [ ! -f "$history_file" ]; then
        touch "$history_file"
    fi

    echo "$history_file"
}

function get_blacklist() {
    configdir=${XDG_CONFIG_HOME:-"$HOME/.config"}

    if [ -d "$configdir" ]; then
        mkdir -p "$configdir"/rmenu &>/dev/null
        config_file="$configdir/rmenu/blacklist"
    else
        config_file="$HOME/.rmenu_blacklist" # if no xdg dir, fall back to dotfiles in ~
    fi

    echo "$config_file"
}

function check_command() {
    if ! command -v "$1" &> /dev/null; then
        echo "\"$1\" could not be found, but is required."
        exit 1
    fi
}

# Ensure fd exists
check_command fd
# Ensure rmenu exists
check_command rmenu
# Ensure rmenu_history exists
check_command rmenu_history

BLACKLIST=$(sort "$(get_blacklist)")

APP_SOURCES=("/Applications" "$HOME/Applications" "/System/Applications" "/System/Applications/Utilities" "/System/Library/CoreServices")
APPS=$(comm -23 <(fd . -e app --exact-depth 1 "${APP_SOURCES[@]}" | sort) <(echo "$BLACKLIST") | sed 's:.*/\(.*\)\.app/:\1:')

PREFERENCE_SOURCES=("/Library/PreferencePanes" "$HOME/Library/PreferencePanes" "/System/Library/PreferencePanes")
PREFERENCES=$(comm -23 <(fd . -e prefPane --exact-depth 1 "${PREFERENCE_SOURCES[@]}" | sort) <(echo "$BLACKLIST") | sed 's:.*/\(.*\)\.prefPane/:\1:')

HISTORY_FILE=$(get_history_file)
SELECTED_APP=$(cat <(echo "$APPS") <(echo "$PREFERENCES") | rmenu_history "$HISTORY_FILE" sort | rmenu "$@")

# If nothing was selected exit
if [[ -z $SELECTED_APP ]]; then
    exit
fi

if grep "^$SELECTED_APP\$" <<<"$APPS" &>/dev/null; then
    # If selection was an app start it
    open -a "$SELECTED_APP"
else
    # if selection was a preference pane start it
    SELECTED_PREFERENCE=$(fd "$SELECTED_APP" -e prefPane --exact-depth 1 "${PREFERENCE_SOURCES[@]}")
    open -b com.apple.systempreferences "$SELECTED_PREFERENCE"
fi

# Update history file with selection
rmenu_history "$HISTORY_FILE" update "$SELECTED_APP"
