#!/usr/bin/env bash

function get_cache_file() {
    cache_dir=${XDG_CACHE_HOME:-"$HOME/.cache"}

    if [ -d "$cache_dir" ]; then
        mkdir -p "$cache_dir/rmenu" &>/dev/null
        cache_file="$cache_dir/rmenu/repos_cache"
    else
        cache_file="$HOME/.rmenu_repos_cache" # if no xdg dir, fall back to dotfile in ~
    fi

    if [ ! -f "$cache_file" ]; then
        touch "$cache_file"
    fi

    echo "$cache_file"
}

function get_history_file() {
    cache_dir=${XDG_CACHE_HOME:-"$HOME/.cache"}

    if [ -d "$cache_dir" ]; then
        mkdir -p "$cache_dir/rmenu" &>/dev/null
        history_file="$cache_dir/rmenu/repos_history"
    else
        history_file="$HOME/.rmenu_repos_history" # if no xdg dir, fall back to dotfile in ~
    fi

    if [ ! -f "$history_file" ]; then
        touch "$history_file"
    fi

    echo "$history_file"
}

function check_commands() {
    for command in "$@"; do
        if ! command -v "$command" &> /dev/null; then
            echo "'$command' could not be found, but is required."
            exit 1
        fi
    done
}

check_commands rmenu rmenu_history

CACHE_FILE=$(get_cache_file)
CACHE=$(cat $CACHE_FILE)

if [[ -z $CACHE ]]; then
    REPOS=$(gh repo list "$GITHUB_ORG" --no-archived --json name --jq '.[].name' -L 1000)
else
    REPOS=$CACHE
fi


HISTORY_FILE=$(get_history_file)

SELECTED_REPO=$(cat <(echo "$REPOS") | rmenu_history "$HISTORY_FILE" sort | rmenu "$@")

# If nothing was selected exit
if [[ -z $SELECTED_REPO ]]; then
    exit
fi

gh repo view "$GITHUB_ORG/$SELECTED_REPO" --web

# Update history file with selection
rmenu_history "$HISTORY_FILE" update "$SELECTED_REPO"

# Update cache file
if [[ -z $CACHE ]]; then
    CACHE=$REPOS
else
    CACHE=$(gh repo list "$GITHUB_ORG" --no-archived --json name --jq '.[].name' -L ${NUMBER_OF_REPOS:-1000})
fi
echo $CACHE | tr " " "\n" > $CACHE_FILE
